--- ADMÝN ( yönetici) TABLOSU ÝÞLEMLERÝ
  CREATE TABLE "SYSTEM"."ADMIN" 
   (	"USER_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"FNAME" VARCHAR2(20 BYTE), 
	"LNAME" VARCHAR2(20 BYTE), 
	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "ADMIN_UK1" UNIQUE ("USER_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "ADMIN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 
--admýn ýdsinin otomatik artmasýný saðlayan trigger
  CREATE OR REPLACE TRIGGER "SYSTEM"."ADMIN_TRG" 
BEFORE INSERT ON ADMIN
FOR EACH ROW 
 WHEN (NEW.ID IS NULL OR NEW.ID=0) BEGIN
  :NEW.ID:=admýn_ID_SEQ.nextval;
END admýn_TRG  ;
/
ALTER TRIGGER "SYSTEM"."ADMIN_TRG" ENABLE;
-------------------------------------------------------
--BÖLÜM TABLOSU ÝÞLEMELRÝ
 CREATE TABLE "SYSTEM"."BOLUM" 
   (	"BOLUMID" NUMBER(*,0) NOT NULL ENABLE, 
	"BOLUMADI" VARCHAR2(50 BYTE), 
	 CONSTRAINT "BOLUM_PK" PRIMARY KEY ("BOLUMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 
--bölüm ýdsinin otomatik artmasýný saðlayan trigger
  CREATE OR REPLACE TRIGGER "SYSTEM"."BOLUM_TRG" 
BEFORE INSERT ON BOLUM 
FOR EACH ROW 
 WHEN (NEW.BOLUMID IS NULL OR NEW.BOLUMID=0) BEGIN
  :NEW.BOLUMID:=BOLUM_ID_SEQ.nextval;
END BOLUM_TRG ;
/
ALTER TRIGGER "SYSTEM"."BOLUM_TRG" ENABLE;
 ------------------------------------------------------------
 --BORCLAR TABLOSU ÝÞLEMLERÝ
 
  CREATE TABLE "SYSTEM"."BORCLAR" 
   (	"BKAYITNO" VARCHAR2(20 BYTE), 
	"KALANBORC" NUMBER(*,0) DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 --KALAN BORÇ MÝKTARINI HESAPLAYAN PROCEDURE
 --ÖÐRENCÝ BORÇ ÖDEMESÝ YAPTIGINDA ÇALIÞTIRILIR
create or replace PROCEDURE BORC 
(
  KAYITNO IN VARCHAR2 
, ODEME IN NUMBER 
) AS 
BEGIN
UPDATE BORCLAR SET KALANBORC=KALANBORC-ODEME WHERE BKAYITNO=KAYITNO;
END BORC;

--ODANIN KAPASÝTESÝNE GÖRE BORÇ TABLOSUNA BORÇ EKLEYEN PROCEDURE 
--BU PROCEDURE YENÝ ÖÐRENCÝ EKLENDÝÐÝNDE ÇALIÞIR
create or replace PROCEDURE BORC_G 
(
  KAYITNOO IN VARCHAR2 
, ODAA IN VARCHAR2 
) AS 
KAPASÝTE INT;
BORC INT;
BEGIN
SELECT  ODA_KAPASÝTE  INTO KAPASÝTE FROM ODA WHERE oda_no=odaa;
CASE
WHEN KAPASÝTE  =1 THEN BORC:=26000;
WHEN KAPASÝTE  =2 THEN BORC:=22000;
WHEN KAPASÝTE  =3 THEN BORC:=19000;
WHEN KAPASÝTE  =4 THEN BORC:=16000;
END CASE;
update BORCLAR set kalanborc=BORC WHERE bkayýtno=kayýtnoo;
END BORC_G;
--------------------------------------------------------
--ÝZÝNLER TABLOSU

  CREATE TABLE "SYSTEM"."IZINLER" 
   (	"IKAYIT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"BAS" DATE NOT NULL ENABLE, 
	"SON" DATE NOT NULL ENABLE, 
	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ACIKLAMA" VARCHAR2(50 BYTE), 
	 CONSTRAINT "IZINLER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 --ÝZÝN ID OTOMATÝK ARTMASINI SAÐLAR

  CREATE OR REPLACE TRIGGER "SYSTEM"."IZIN_TRG" 
BEFORE INSERT ON IZINLER
FOR EACH ROW 
 WHEN (NEW.ID IS NULL OR NEW.ID=0) BEGIN
  :NEW.ID:=IZIN_ID_SEQ.nextval;
  END IZIN_TRG ;
/
ALTER TRIGGER "SYSTEM"."IZIN_TRG" ENABLE;
 

---------------------------------------------------
--KASA TABLOSU
--ÖDEMELER BURAYA KAYIT EDÝLÝR

  CREATE TABLE "SYSTEM"."KASA" 
   (	"ODEMEAY" VARCHAR2(20 BYTE), 
	"ÖDEMEMÝKTARI" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 
----------------------------------------------
---ODA TABLOSU ÝÞLEMELRÝ

  CREATE TABLE "SYSTEM"."ODA" 
   (	"ODA_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ODA_NO" CHAR(3 BYTE) NOT NULL ENABLE, 
	"ODA_A" CHAR(1 BYTE) DEFAULT 0, 
	"ODA_DURUM" CHAR(1 BYTE), 
	"ODA_KAPASÝTE" CHAR(1 BYTE), 
	 CONSTRAINT "ODA_PK" PRIMARY KEY ("ODA_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 
--ODA ID OTOMATÝK ARTIÞ
  CREATE OR REPLACE TRIGGER "SYSTEM"."ODA_TRG" 
BEFORE INSERT ON ODA
FOR EACH ROW 
 WHEN (NEW.ODA_ID IS NULL OR NEW.ODA_ID=0) BEGIN
  :NEW.ODA_ID:=oda_ID_SEQ.nextval;
  END oda_TRG;
/
ALTER TRIGGER "SYSTEM"."ODA_TRG" ENABLE;
 
----------------------------------------------------------
---ÖDEMELER TABLOSU YURT GÝDERLERÝ BURADA TUTULUR

  CREATE TABLE "SYSTEM"."ODEMELER" 
   (	"ODEMEID" NUMBER(*,0) NOT NULL ENABLE, 
	"ELEKTRIK" NUMBER(*,0), 
	"SU" NUMBER(*,0), 
	"DOGALGAZ" NUMBER(*,0), 
	"INTERNET" NUMBER(*,0), 
	"GIDA" NUMBER(*,0), 
	"PERSONEL" NUMBER(*,0), 
	"DIGER" NUMBER(*,0), 
	 CONSTRAINT "ODEMELER_PK" PRIMARY KEY ("ODEMEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 
---ODEME ID OTOMATÝK ARTIÞ TRIGGER
  CREATE OR REPLACE TRIGGER "SYSTEM"."ODEME_TRG1" 
BEFORE INSERT ON ODEMELER 
FOR EACH ROW 
 WHEN (NEW.ODEMEID IS NULL OR NEW.ODEMEID=0) BEGIN
  :NEW.ODEMEID:=ODEMELER_ID_SEQ.nextval;
END ODEME_TRG;
/
ALTER TRIGGER "SYSTEM"."ODEME_TRG1" ENABLE;
 

-----------------------------------------
---ÞÝKAYET TABLOSU
  CREATE TABLE "SYSTEM"."SIKAYET" 
   (	"ODAID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"YORUM" VARCHAR2(50 BYTE), 
	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "SIKAYET_PK" PRIMARY KEY ("ID", "ODAID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 
--ÞÝKAYET ID OTOMATÝK ARTIÞ TRIGGER
  CREATE OR REPLACE TRIGGER "SYSTEM"."SÝKAYET_TRG" 
BEFORE INSERT ON SIKAYET
FOR EACH ROW 
 WHEN (NEW.ID IS NULL OR NEW.ID=0) BEGIN
  :NEW.ID:=SIKAYET_ID_SEQ.nextval;
  END SÝKAYET_TRG;
/
ALTER TRIGGER "SYSTEM"."SÝKAYET_TRG" ENABLE;
 
-----------------------------------------------------
---ÖÐRENCÝ TABLOSU 

  CREATE TABLE "SYSTEM"."STUDENT" 
   (	"FNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"LNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"TCNO" CHAR(11 BYTE) NOT NULL ENABLE, 
	"BDATE" DATE, 
	"BOLUM" NUMBER(*,0) DEFAULT 0, 
	"E_POSTA" VARCHAR2(20 BYTE), 
	"TEL_NO" CHAR(11 BYTE), 
	"ODA_NO" CHAR(3 BYTE), 
	"KAYITNO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "STUDENT_PK22" PRIMARY KEY ("KAYITNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 FOREIGN KEY ("KAYITNO")
	  REFERENCES "SYSTEM"."USER_STD" ("KAYITNO") ENABLE, 
	 CONSTRAINT "STUDENT1_FK1" FOREIGN KEY ("KAYITNO")
	  REFERENCES "SYSTEM"."VELI_B" ("VKAYITNO") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

 
--- ÖÐRENCÝ TABLOSUNDA ODA NO GÜNCELLENDÝÐÝNDE ÇALIÞIR
-- ÖÐRENCÝNÝN ODA NUMARASINA  GÖRE  ODADA AKTÝF OLARAK KALAN ÖÐRENCÝ SAYISINI DEÐÝÞTÝRÝR.

  CREATE OR REPLACE TRIGGER "SYSTEM"."OD_GÜNCELLE_OGRENCÝ" 
BEFORE UPDATE OF ODA_NO ON STUDENT 
FOR EACH ROW 
 WHEN (OLD.ODA_NO!=NEW.ODA_NO) BEGIN
UPDATE ODA SET ODA_A=ODA_A-1 WHERE oda_no=:OLD.ODA_NO;
UPDATE ODA SET ODA_A=ODA_A+1 WHERE oda_no=:NEW.ODA_NO;
  NULL;
END OD_GÜNCELLE_OGRENCÝ ;
/
ALTER TRIGGER "SYSTEM"."OD_GÜNCELLE_OGRENCÝ" ENABLE;
 
 ----ÖÐRENCÝ SÝLÝNDÝÐÝNDE,ÖÐRENCÝNÝN  KALDIÐI ODANIN AKTÝF ÖÐRENCÝ SAYISI 1 AZALTAN TRIGGER
  CREATE OR REPLACE TRIGGER "SYSTEM"."ODAAKTIF_TGR2" 
AFTER DELETE ON STUDENT 
FOR EACH ROW 
BEGIN
UPDATE ODA SET oda_a=ODA_A-1 WHERE oda_no=:OLD.ODA_NO;
END ODAAKTIF_TGR2 ;
/
ALTER TRIGGER "SYSTEM"."ODAAKTIF_TGR2" ENABLE;
 
 ---ÖÐRENCÝ EKLENDÝÐÝNDE ,ÖÐRENCÝNÝN  KALDIÐI ODANIN AKTÝF ÖÐRENCÝ SAYISI 1 ARTTIRAN TRIGGER

  CREATE OR REPLACE TRIGGER "SYSTEM"."ODAAKTIF_TGR" 
AFTER INSERT ON STUDENT 
FOR EACH ROW 
BEGIN
UPDATE ODA SET oda_a=ODA_A+1 WHERE oda_no=:NEW.ODA_NO;
END ODAAKTIF_TGR ;
/
ALTER TRIGGER "SYSTEM"."ODAAKTIF_TGR" ENABLE;
 
--ÖÐRENCÝ SÝLÝNDÝÐÝNDE DÝÐER TABLOLARDAKÝ ÖÐRENCÝYE AÝT BÝLGÝLERÝ SÝLEN PROCEDURE
create or replace PROCEDURE SILME_PR 
(
  KAYITNOO IN VARCHAR2 
) AS 
BEGIN
DELETE FROM USER_STD WHERE kayýtno=kayýtnoo;
DELETE FROM BORCLAR WHERE BKAYITNO=kayýtnoo;
DELETE FROM IZINLER WHERE IKAYIT=kayýtnoo;
  
END SILME_PR;
----------------------------------------
--ÖÐRENCÝ KULLANICI ADLARININ TUTULDUÐU TABLO
  CREATE TABLE "SYSTEM"."USER_STD" 
   (	"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"KAYITNO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "USER_STD_PK" PRIMARY KEY ("KAYITNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "USER_STD_UK1" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

----------------------------------------
--VELÝ TABLOSU

  CREATE TABLE "SYSTEM"."VELI_B" 
   (	"VFNAME" VARCHAR2(20 BYTE), 
	"VLNAME" VARCHAR2(20 BYTE), 
	"VTEL_NO" NUMBER, 
	"VKAYITNO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"VADRES" VARCHAR2(50 BYTE), 
	 CONSTRAINT "VELI_B_PK" PRIMARY KEY ("VKAYITNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 








